### ISSUE TITLE
Not render the fields specified by user

### ISSUE THREAD

**Issue by semkagtn** [kubukoz/better-tostring#1]
The plugin is really useful. Thanks for it!

IMO it would be super-great to add the functionality that allows to you removing some fields from string representation. For example:

Default:
```scala
case class User(id: Int,
                name: String,
                data: Seq[Byte])
User(1, "user-name", List(42)).toString
// User(id = 1, name = user-name, data = List(42))
```

Customized:
```scala
case class User(id: Int,
                name: String,
                @bettertostring.ignore data: Seq[Byte])
User(1, "user-name", List(42)).toString
// User(id = 1, name = user-name)
// or User(id = 1, name = user-name, data)
```

I'm not sure that annotation name is good, but my idea should be clear :)

**Comment by kubukoz** [comment]
I plan to do this, but unless I'm missing something it'll require you to add a library dependency that contains the annotation.

I should be able to work on this later this week :)

**Comment by kubukoz** [comment]
@semkagtn btw. thanks for submitting!

Which behavior do you think would work best, skipping the field altogether or replacing it with a constant? Should that constant be configurable, or `<bettertostring.ignored>` / `<ignored>`?

**Comment by semkagtn** [comment]
@kubukoz 
I can imagine three possible ways to represent the string:
(1) `User(id = 1, name = user-name, data = <hidden>) // The most obvious`.  
(2) `User(id = 1, name = user-name, data) // Shorter`
(3) `User(id = 1, name = user-name) // Not obvious. But the shortest`.

I think that the annotation shouldn't have any parameters.

It's better to add  some compiler options to set the behaviour globally. For example:
`-P:bettertostring:longest // turn on (1)`
`-P:bettertostring:shorter // turn on (2)`
`-P:bettertostring:shortest // turn on (3)`
Also you can add the parameter to change the `<hidden>` value to 
something else.

P.S. Not sure the names of the parameters are proper. Just an idea.

**Comment by kubukoz** [comment]
> @kubukoz
> I can imagine three possible ways to represent the string:
> (1) `User(id = 1, name = user-name, data = <hidden>) // The most obvious`.
> (2) `User(id = 1, name = user-name, data) // Shorter`
> (3) `User(id = 1, name = user-name) // Not obvious. But the shortest`.
> 
> I think that the annotation shouldn't have any parameters.
> 
> It's better to add some compiler options to set the behaviour globally. For example:
> `-P:bettertostring:longest // turn on (1)`
> `-P:bettertostring:shorter // turn on (2)`
> `-P:bettertostring:shortest // turn on (3)`
> Also you may add the parameter to change the `<hidden>` value to
> something else.

If the feature is going to appear at all, I want it to be locally configurable. I can already foresee people asking about that if they want exceptions - might as well just have everyone specify the format directly at the annotation.

Additionally, I like to avoid changing the build definition as much as possible, so I'd rather stay away from flag-based configuration.

> P.S.S. **Offtopic** Additionally you may add an option to remove formatting spaces to make the string representation shorter. For example: `User(id = 1, name = user-name)` => `User(id=1,name=user-name)`. Personally, I prefer the representation without spaces.

This might actually be sensible as a global setting, but to be honest I don't think there's much value in having more concise representations. `toString` is meant to be readable for humans and having less whitespace isn't going to help that. I also don't want to support every single possible use case, so the plugin is going to be a little opinionated in certain areas, such as this :)

**Comment by semkagtn** [comment]
> If the feature is going to appear at all, I want it to be locally configurable. I can already foresee people asking about that if they want exceptions - might as well just have everyone specify the format directly at the annotation.
As you want :)
But in my opinion the typical case is when you want set the formatting options globally. So if formatting will be configurable locally then the most of users will have to repeat their configuration everywhere.
Actually this formatting tuning isn't so important. It may be implemented in far future if necessary :)

> (I'm still wondering if it's not better to just show everything and ask users to implement their own `toString`)
I'm completely sure it's a very useful and convenient feature.
If your class contains 20+ fields it's pretty boring to write your own `toString` implementation (because you want don't show only one field!). In addition, when adding a new field, you shouldn't forget to rewrite the `toString` method (of course, it isn't as critical as `equals` or `hashCode` methods, but!).

**Comment by kubukoz** [comment]
I gave it some thought, and I think the plugin should stay minimal - its main purpose is changing the default globally so that it doesn't need to be adjusted on an individual basis.

For cases like yours, I would suggest looking into some generic derivation mechanisms like magnolia or shapeless, and using that to derive a toString implementation that skips certain types.
