### ISSUE TITLE
Cross-build to Scala 3.0.0-RC2

### ISSUE THREAD

**Issue by kubukoz** [kubukoz/better-tostring#17]
This requires:

- adding 3.0.0-RC2 to the list of cross scala versions in `build.sbt`
- adding the version to the README
- afterwards, pushing a tag (`v0.2.9` at this moment, basically patch update)

~Also might want to upgrade sbt to 1.5.0-RC2 and remove sbt-dotty in favor of that.~ this is handled in #20

**Comment by majk-p** [comment]
I guess this has to wait for scalatest:
```
[error] stack trace is suppressed; run last tests / update for the full output
[error] (tests / update) sbt.librarymanagement.ResolveException: Error downloading org.scalatest:scalatest_3.0.0-RC2:3.2.5
[error]   Not found
```
It seems it's still on RC1 https://github.com/scalatest/scalatest/blob/3.2.x-new/project/DottyBuild.scala#L15

**Comment by kubukoz** [comment]
https://github.com/scalatest/scalatest/releases/tag/release-3.2.7
